
deployer:
  custom_policies:
    cloudfront_invalidation:
      action:
        - cloudfront:CreateInvalidation
      resource: 
        - '*'
    s3_source:
      action:
        - s3:GetObject
      resource:
        - Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: DeploymentSourceBucket
            - /*
    s3_dest:
      action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      resource:
        - Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: DeploymentBucket
            - /*
  roles:
    default:
      policies_inline:
        - cloudwatch-logs
        - s3_source
        - s3_dest
  functions:
    S3Deployer:
      role: default
      code: lambdas/s3_deployer.py
      runtime: python3.9
      timeout: 120
      handler: s3_deployer.handler
